### ISSUE TITLE
checking if persistence layer returns undefined/null

### ISSUE THREAD

**Issue by TVLuke** [Chaotikum/icebox-service#3]
At several points we request an object from the persistence-layer and then access data from it. Sometimes, if bad/empty parameters wehre transmitted, the data from the persistence-layer is null/undefined. Right now, this crashes the entire system...

**Comment by johthor** [comment]
So should we add more callbacks to handle the undefined cases or should we add something like null objects?

**Comment by TVLuke** [comment]
No sure. Maybe the callbacks you introduced into persistence/consumers.js even handles these problems already (callback with two parameters...). Up till now I have only been able to crash drinks.js and consumptions.js...

**Comment by TVLuke** [comment]
at this point... i guess we checked.
